name: EAS Build Workflow

on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, labeled]

jobs:
  build_android:
    name: Build Android App
    type: build
    params:
      platform: android
      # Dynamically choose profile based on the branch
      profile: ${{ github.ref_name == 'master' && 'production' || 'preview' }}
